# Site settings
language:               "en"
title:                  "The Vantage Project"
description:            "We help daring entrepreneurs build vantage"
google-verification:    "XClNz4rZr5JJ4Caeh1_ywN2E74ZNj4NGt45o1wnqloU"

# Handling Reading
include:
  - ".htaccess"
  - "_pages"
  - "playbook/"

exclude:
  - ".DS_Store"
  - "blog"
  # - "/assets/"
  - "bower.json"
  - "bower_components"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "yarn.lock"
  - "yarn-error.log"

# Plugins
# Add plugins in the Gemfile
plugins:             ["jekyll-sitemap"]


# Conversion
incremental:      true

# Serving
# url: http://127.0.0.1.xip.io:3000
url:            "https://www.thevantageproject.com"
# url: https://thevantageproject.github.io/web
# baseurl:        "" # does not include hostname

# Outputting
# permalink:        "/blog/:year/:title/"
permalink: "/:title"
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]

highlighter:      rouge

defaults:
  -
    scope:
      path:            "assets/"
    values:
      sitemap:         false
